console.log('hello');
console.log('hello');
console.log('hello');
// let a=0;
//if the value is not intialize or not get error then try run if any type of error find then catch handle that
try{
console.log(a);
}
catch{
    console.log('error');
}
console.log('hello');
console.log('hello');

